### ISSUE TITLE
handling of service start and stop

### ISSUE THREAD

**Issue by b08x** [syncopatedstudios/soundbot#15]
`[d7965aa2] Finished in 0.085 seconds with exit status 1 (failed)
error: Running `a2j_control --start` failed with
  exit status: 1
  stdout: --- start
  stderr: Traceback (most recent call last):
  File "/usr/bin/a2j_control", line 203, in <module>
    A2JControl()
  File "/usr/bin/a2j_control", line 199, in __init__
    self.call_controller_function()
  File "/usr/bin/a2j_control", line 166, in call_controller_function
    self.controller_start()
  File "/usr/bin/a2j_control", line 94, in controller_start
    self.controller_interface.start()
  File "/usr/lib/python3.8/site-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3.8/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3.8/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.gna.home.a2jmidid.error.generic: a2j_start() failed.
. Use --trace to view backtrace
`

**Comment by b08x** [comment]
leaving this to the jackd systemd issue
